# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('e63cacbd34ec507ebef58ff6cd6196a2_MjAzNTk0MjAxMy0wMy0yNSAxMDoxNzoxMy4zOTY4NzQ')
  end)
end
