// Generated by IB v0.3.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation Camera

@end


@implementation UIView

@end


@implementation UIAlertView

@end


@implementation ClickedButton

@end


@implementation UIViewController

@end


@implementation InvalidURLError

@end


@implementation InvalidFileError

@end


@implementation BubbleWrap

@end


@implementation BubbleWrap

@end


@implementation AppDelegate

@end


@implementation TopicController

@end


@implementation TopicsController

@end



